### ISSUE TITLE
What questions/insights can we answer with the dataset.

### ISSUE THREAD

**Issue by Novotern** [Novotern/Nigeria-Farmland-App#3]

**Comment by emmanuelani** [comment]
- What is the most common source of electricity among farmers?
- Which type of farming is mostly practiced?
- Create a visualization of the location of each farmland.

**Comment by Kehnnie** [comment]
-  What is the distribution of farm types and which type is most prevalent among the listed farms
- Which farm category is the primary focus for agricultural processes
- How many farms has a processing facilty and the percentage

**Comment by Novotern** [comment]
Great. Let's start answering those questions.
